services:
  - type: web
    name: ajb-imports
    runtime: node
    plan: starter
    buildCommand: npm ci
    startCommand: node server.js
    healthCheckPath: /api/status
    envVars:
      - key: NODE_ENV
        value: production
      - key: GOOGLE_DATA_DIR
        value: /var/data
      - key: GOOGLE_SHEET_ID
        value: https://docs.google.com/spreadsheets/d/1JO6Qhr83CIOrO5Ps25EVgJiW-A6pislD/edit?gid=158840977#gid=158840977
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        value: ""
      - key: GOOGLE_SHEET_TAB
        value: Quote Submissions
    disk:
      name: quote-submissions
      mountPath: /var/data
      sizeGB: 1
